// ui/src/bichat/components/EmptyState.tsx
/**
 * EmptyState Component
 * Reusable empty state display with icon, title, description, and action
 */

import { memo, type ReactNode } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { fadeInVariants } from '../animations/variants'

export interface EmptyStateProps {
  /** Optional icon to display */
  icon?: ReactNode
  /** Main title text */
  title: string
  /** Optional description text */
  description?: string
  /** Optional action element (button, link, etc.) */
  action?: ReactNode
  /** Additional CSS classes */
  className?: string
  /** Size variant */
  size?: 'sm' | 'md' | 'lg'
}

const sizeClasses = {
  sm: {
    container: 'py-6 px-3',
    title: 'text-sm',
    description: 'text-xs',
  },
  md: {
    container: 'py-8 px-4',
    title: 'text-base',
    description: 'text-sm',
  },
  lg: {
    container: 'py-12 px-6',
    title: 'text-lg',
    description: 'text-base',
  },
}

function EmptyState({
  icon,
  title,
  description,
  action,
  className = '',
  size = 'md',
}: EmptyStateProps) {
  const sizes = sizeClasses[size]
  const prefersReducedMotion = useReducedMotion()
  const duration = prefersReducedMotion ? 0 : 0.4

  return (
    <motion.div
      className={`flex items-center justify-center ${sizes.container} ${className}`}
      variants={fadeInVariants}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      <div className="text-center max-w-md">
        {/* Icon */}
        {icon && (
          <motion.div
            className="mb-4 flex justify-center"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration, delay: prefersReducedMotion ? 0 : 0.1 }}
          >
            {icon}
          </motion.div>
        )}

        {/* Title */}
        <motion.h3
          className={`${sizes.title} font-medium text-gray-900 dark:text-white mb-2`}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration, delay: prefersReducedMotion ? 0 : 0.2 }}
        >
          {title}
        </motion.h3>

        {/* Description */}
        {description && (
          <motion.p
            className={`${sizes.description} text-gray-500 dark:text-gray-400 mb-4`}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration, delay: prefersReducedMotion ? 0 : 0.3 }}
          >
            {description}
          </motion.p>
        )}

        {/* Action */}
        {action && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration, delay: prefersReducedMotion ? 0 : 0.4 }}
          >
            {action}
          </motion.div>
        )}
      </div>
    </motion.div>
  )
}

const MemoizedEmptyState = memo(EmptyState)
MemoizedEmptyState.displayName = 'EmptyState'

export { MemoizedEmptyState as EmptyState }
export default MemoizedEmptyState

// web/chat-ui/src/components/EmptyState.tsx
import { createReducedMotion } from '../hooks/createReducedMotion';
import { type JSX, mergeProps, createSignal, createMemo, createEffect, on, onMount, onCleanup, untrack, createContext, useContext, lazy, Suspense, createUniqueId, Show, For } from "solid-js";
import { fadeInVariants } from '../animations/variants';
export interface EmptyStateProps {
    /** Optional icon to display */
    icon?: JSX.Element;
    /** Main title text */
    title: string;
    /** Optional description text */
    description?: string;
    /** Optional action element (button, link, etc.) */
    action?: JSX.Element;
    /** Additional CSS classes */
    className?: string;
    /** Size variant */
    size?: 'sm' | 'md' | 'lg';
}
const sizeClasses = {
    sm: {
        container: 'py-6 px-3',
        title: 'text-sm',
        description: 'text-xs',
    },
    md: {
        container: 'py-8 px-4',
        title: 'text-base',
        description: 'text-sm',
    },
    lg: {
        container: 'py-12 px-6',
        title: 'text-lg',
        description: 'text-base',
    },
};
function EmptyState(solidProps1Input: EmptyStateProps) {
    const solidProps1 = mergeProps({ className: '', size: 'md' } as const, solidProps1Input);
    const sizes = createMemo(() => sizeClasses[solidProps1.size]);
    const prefersReducedMotion = createReducedMotion();
    const duration = prefersReducedMotion() ? 0 : 0.4;
    return (<div class={`flex items-center justify-center ${sizes().container} ${solidProps1.className}`}>
      <div class="text-center max-w-md">
        {/* Icon */}
        {solidProps1.icon && (<div class="mb-4 flex justify-center">
            {solidProps1.icon}
          </div>)}

        {/* Title */}
        <h3 class={`${sizes().title} font-medium text-gray-900 dark:text-white mb-2`}>
          {solidProps1.title}
        </h3>

        {/* Description */}
        {solidProps1.description && (<p class={`${sizes().description} text-gray-500 dark:text-gray-400 mb-4`}>
            {solidProps1.description}
          </p>)}

        {/* Action */}
        {solidProps1.action && (<div>
            {solidProps1.action}
          </div>)}
      </div>
    </div>);
}
const MemoizedEmptyState = EmptyState;
MemoizedEmptyState; /* Solid components are named by their declarations. */
export { MemoizedEmptyState as EmptyState };
export default MemoizedEmptyState;
