// web/client-host/src/solid-portals.ts
import { createComponent, createContext, createEffect, createUniqueId, onCleanup, onMount, useContext, type JSX } from 'solid-js'
import { insert } from 'solid-js/web'
import { PortalRegistry, type PortalSurface, type WidgetSlotName } from './portal-host'

export type { PortalSurface, WidgetSlotName } from './portal-host'

export interface SolidPortalHost {
  registry: PortalRegistry
  slots: ReadonlyMap<WidgetSlotName, HTMLElement>
  registerCleanup(cleanup: () => void): () => void
}

const PortalHostContext = createContext<SolidPortalHost>()

export function SolidPortalHostProvider(props: { host: SolidPortalHost; children: JSX.Element }): JSX.Element {
  return createComponent(PortalHostContext.Provider, {
    value: props.host,
    get children() { return props.children },
  })
}

export interface PortalProps {
  surface: PortalSurface
  label: string
  class?: string
  className?: string
  onEscape?: () => void
  theme?: 'light' | 'dark'
  children?: JSX.Element
}

const focusableSelector = 'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'

export function Portal(props: PortalProps): JSX.Element {
  const host = useContext(PortalHostContext)
  if (!host) throw new Error('Portal must be rendered inside a mounted Solid client route with a portal owner')

  const id = createUniqueId()
  const document = host.registry.root(props.surface).ownerDocument
  const content = document.createElement('div')
  const marker = document.createTextNode('')
  const activeElement = document.activeElement
  const restore = activeElement && 'focus' in activeElement ? activeElement as HTMLElement : null
  let unmountOverlay: () => void = () => undefined
  let unregisterHostCleanup: () => void = () => undefined
  let cleaned = false

  insert(content, () => props.children)
  createEffect(() => {
    content.className = props.class ?? props.className ?? ''
    content.dataset.iotaSurface = props.surface
    if (props.theme) content.dataset.theme = props.theme
    else delete content.dataset.theme
  })
  content.setAttribute('role', props.surface === 'toast' ? 'status' : 'dialog')
  content.setAttribute('aria-label', props.label)
  content.tabIndex = -1
  if (props.surface !== 'toast') content.setAttribute('aria-modal', 'true')

  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key === 'Escape' && props.onEscape) {
      event.preventDefault()
      event.stopPropagation()
      props.onEscape()
      return
    }
    if (event.key !== 'Tab' || props.surface === 'toast') return
    const focusable = Array.from(content.querySelectorAll<HTMLElement>(focusableSelector))
    if (focusable.length === 0) {
      event.preventDefault()
      content.focus()
      return
    }
    const first = focusable[0]
    const last = focusable.at(-1)
    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault()
      last?.focus()
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault()
      first?.focus()
    }
  }
  content.addEventListener('keydown', onKeyDown)

  const cleanup = () => {
    if (cleaned) return
    cleaned = true
    content.removeEventListener('keydown', onKeyDown)
    content.remove()
    unmountOverlay()
    unregisterHostCleanup()
  }
  onMount(() => {
    host.registry.root(props.surface).append(content)
    unmountOverlay = host.registry.mount({ id, surface: props.surface, restore })
    unregisterHostCleanup = host.registerCleanup(cleanup)
    if (props.surface !== 'toast') (content.querySelector<HTMLElement>(focusableSelector) ?? content).focus()
  })
  onCleanup(cleanup)

  return marker
}

export function WidgetSlot(props: { name: WidgetSlotName; children?: JSX.Element }): JSX.Element {
  const host = useContext(PortalHostContext)
  const slot = host?.slots.get(props.name)
  if (!slot) return undefined
  const container = slot.ownerDocument.createElement('div')
  const marker = slot.ownerDocument.createTextNode('')
  let unregisterHostCleanup: () => void = () => undefined
  let cleaned = false
  container.style.display = 'contents'
  insert(container, () => props.children)
  const cleanup = () => {
    if (cleaned) return
    cleaned = true
    container.remove()
    unregisterHostCleanup()
  }
  onMount(() => {
    slot.append(container)
    unregisterHostCleanup = host?.registerCleanup(cleanup) ?? (() => undefined)
  })
  onCleanup(cleanup)
  return marker
}

// web/client-host/src/portals.tsx
import { createContext, type KeyboardEvent, type PropsWithChildren, type ReactNode, useContext, useEffect, useId, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { PortalRegistry, type PortalSurface, type WidgetSlotName } from './portal-host'

export type { PortalSurface, WidgetSlotName } from './portal-host'

const PortalContext = createContext<PortalRegistry | undefined>(undefined)
const WidgetContext = createContext<ReadonlyMap<WidgetSlotName, HTMLElement>>(new Map())

export interface ClientHostProviderProps extends PropsWithChildren {
  portalOwner: HTMLElement
  background?: HTMLElement | undefined
  widgetSlots?: Partial<Record<WidgetSlotName, HTMLElement>> | undefined
  theme?: 'light' | 'dark' | undefined
}

/** Owns document-lifetime portal roots; feature roots must never append to body. */
export function ClientHostProvider({ portalOwner, background, widgetSlots = {}, theme, children }: ClientHostProviderProps) {
  const registry = useMemo(() => new PortalRegistry(portalOwner, background), [portalOwner, background])
  const slots = useMemo(() => new Map(Object.entries(widgetSlots) as [WidgetSlotName, HTMLElement][]), [widgetSlots])
  useEffect(() => () => registry.destroy(), [registry])
  useEffect(() => {
    const baseTheme = portalOwner.getAttribute('data-theme')
    if (theme) portalOwner.dataset.theme = theme
    return () => {
      if (baseTheme === null) delete portalOwner.dataset.theme
      else portalOwner.setAttribute('data-theme', baseTheme)
    }
  }, [portalOwner, theme])
  return <PortalContext.Provider value={registry}><WidgetContext.Provider value={slots}>{children}</WidgetContext.Provider></PortalContext.Provider>
}

export interface PortalProps extends PropsWithChildren { surface: PortalSurface; label: string; className?: string; onEscape?: () => void; theme?: 'light' | 'dark' }

export function Portal({ surface, label, className, onEscape, theme, children }: PortalProps) {
  const registry = useContext(PortalContext)
  if (!registry) throw new Error('Portal must be rendered inside ClientHostProvider')
  const id = useId()
  const content = useRef<HTMLDivElement>(null)
  useEffect(() => registry.mount({ id, surface, restore: registry.ownerDocument.activeElement as HTMLElement | null }), [id, registry, surface])
  useEffect(() => {
    if (surface === 'toast') return
    const root = content.current
    const first = root?.querySelector<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')
    first?.focus()
  }, [surface])
  const trapFocus = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Escape' && onEscape) { event.preventDefault(); event.stopPropagation(); onEscape(); return }
    if (event.key !== 'Tab' || surface === 'toast') return
    const focusable = Array.from(content.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])') ?? [])
    if (focusable.length === 0) { event.preventDefault(); content.current?.focus(); return }
    const first = focusable[0]
    const last = focusable.at(-1)
    if (event.shiftKey && registry.ownerDocument.activeElement === first) { event.preventDefault(); last?.focus() }
    else if (!event.shiftKey && registry.ownerDocument.activeElement === last) { event.preventDefault(); first?.focus() }
  }
  return createPortal(
    <div ref={content} role={surface === 'toast' ? 'status' : 'dialog'} aria-label={label} aria-modal={surface === 'toast' ? undefined : true} className={className} data-iota-surface={surface} data-theme={theme} onKeyDown={trapFocus} tabIndex={-1}>{children}</div>,
    registry.root(surface),
  )
}

/** Uses an existing standard host when present, otherwise creates a bounded
 * compatibility host inside the feature root (never a body-level root). */
export function ClientHostBoundary({ children, theme }: PropsWithChildren<{ theme?: 'light' | 'dark' | undefined }>) {
  const existing = useContext(PortalContext)
  if (existing) return children
  return <EmbeddedClientHost theme={theme}>{children}</EmbeddedClientHost>
}

function EmbeddedClientHost({ children, theme }: PropsWithChildren<{ theme?: 'light' | 'dark' | undefined }>) {
  const [background, setBackground] = useState<HTMLDivElement | null>(null)
  const [portals, setPortals] = useState<HTMLDivElement | null>(null)
  return <>
    <div data-client-route-background ref={setBackground}>
      {background && portals ? <ClientHostProvider portalOwner={portals} background={background} theme={theme}>{children}</ClientHostProvider> : null}
    </div>
    <div data-client-route-portals ref={setPortals} />
  </>
}

/** Widget slots are persistent shell surfaces and intentionally separate from overlays. */
export function WidgetSlot({ name, children }: { name: WidgetSlotName; children: ReactNode }) {
  const slot = useContext(WidgetContext).get(name)
  return slot ? createPortal(children, slot) : null
}
